//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCoSo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string MSSV { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public string NgaySinh { get; set; }
        public string NoiSinh { get; set; }
        public string GioiTinh { get; set; }
        public string DanToc { get; set; }
        public string TonGiao { get; set; }
        public string Diachithuongtru { get; set; }
        public string Tinh { get; set; }
        public string QuanHuyen { get; set; }
        public string QuocGia { get; set; }
        public string CMND { get; set; }
        public string DoanDang { get; set; }
        public string Uutien { get; set; }
        public string KhuVuc { get; set; }
        public string NamSinh { get; set; }
        public string LoaiSV { get; set; }
        public string DienThoaiDiDong { get; set; }
        public string Email { get; set; }
        public string TenCha { get; set; }
        public string NgheNghiepCha { get; set; }
        public string TenMe { get; set; }
        public string NgheNghiepMe { get; set; }
        public string KhoaHoc { get; set; }
        public string DonVi { get; set; }
        public string TenNghanh { get; set; }
        public string LopSV { get; set; }
        public string NgayCapCMND { get; set; }
    }
}
