//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinhvien
    {
        public string MSSV { get; set; }
        public string Hoten { get; set; }
        public string GioTinh { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public System.DateTime NamSinh { get; set; }
        public string NoiSinh { get; set; }
        public string Diachi { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string TenCha { get; set; }
        public string NgheCha { get; set; }
        public string TenMe { get; set; }
        public string NgheMe { get; set; }
        public string TenNLL { get; set; }
        public string DiaChiNLL { get; set; }
        public string SdtNLL { get; set; }
        public Nullable<int> MaDT { get; set; }
        public Nullable<int> MaTG { get; set; }
        public Nullable<int> MaTT { get; set; }
        public Nullable<int> MaQH { get; set; }
        public string MaKH { get; set; }
        public string MaNH { get; set; }
        public string MaLop { get; set; }
    
        public virtual DanToc DanToc { get; set; }
        public virtual KhoaHoc KhoaHoc { get; set; }
        public virtual Lop Lop { get; set; }
        public virtual NghanhHoc NghanhHoc { get; set; }
        public virtual QuanHuyen QuanHuyen { get; set; }
        public virtual TonGiao TonGiao { get; set; }
        public virtual TinhThanh TinhThanh { get; set; }
    }
}
