//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string MSSV { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public string Lop { get; set; }
        public string Khoa { get; set; }
        public string Sdt { get; set; }
    }
}
